#!/usr/bin/env python3
"""
End-to-end pipeline for manifold analysis.

Implements the pipeline from the MATLAB master scripts:
  - generate_datasets_ncomms2020.m   (dataset generation)
  - generate_results_ncomms2020.m    (analysis: capacity + geometry)

The MATLAB pipeline uses file-based I/O with .mat metadata files generated by
generate_convnet_model_metadata.m and load_network_metadata.m.  Since those
metadata files are tightly coupled to MATLAB conventions, this script instead
calls the core library functions directly (check_binary_dichotomies_capacity,
optimal_low_rank_structure, calc_manifold_properties) on data generated
in-process via PyTorch.

Usage:
  # Small test: AlexNet, 10 objects, 15 samples, 1 direction
  python run_example.py --network_type 1 --n_objects 10 --n_samples 15 \\
      --range_factor 1.0 --directions 0 --output_dir ./test_results

  # Full pipeline: AlexNet, all defaults
  python run_example.py --network_type 1 --output_dir ./results

Network types: 1=alexnet, 3=resnet50, 5=vgg16
"""

import argparse
import math
import os
import sys
import time

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from smooth_manifolds_generation.config import (
    IMAGENET_IMAGE_SIZE,
    IMAGENET_FRAME_SIZE,
    N_HMAX_FEATURES,
)

# ============================================================================
# Constants matching MATLAB generate_results_ncomms2020.m
# ============================================================================

RANGE_FACTORS = [0.125, 0.25, 0.5, 1, 2, 4, 8, 12, 16]
SAMPLES_1D = [5, 9, 15, 27, 51, 101, 201, 201, 201]

DIRECTION_NAMES = [
    'x-translation', 'y-translation', 'x-scale', 'y-scale',
    'x-shear', 'y-shear', 'rotation',
]

# Analysis parameters matching MATLAB defaults
EXPECTED_PRECISION = 0.05
MAX_SAMPLES = 100
FEATURES_TYPE = 2  # 0=sub-sample, 2=random projections
OPTIMIZATION_N_REPEATS = 10


# ============================================================================
# Step 1: Generate tuning functions via PyTorch
# ============================================================================

def generate_tuning_functions(network_type, n_objects, n_samples, range_factor,
                               directions, verbose=True):
    """
    Generate 1D manifold tuning functions:
      1. Create random images (stand-in for ImageNet thumbnails)
      2. Apply 1D affine transforms per direction/sample
      3. Extract features from each network layer via PyTorch

    Returns dict: layer_name -> (N_DIRECTIONS, n_objects, n_samples, n_features)
    """
    import torch
    from smooth_manifolds_generation.feature_extraction import (
        convnet_init, preprocess_image, NETWORK_TYPE_STRINGS,
    )
    from smooth_manifolds_generation.affine_transforms import (
        create_1d_affine_transform,
        calc_imagenet_warp_legacy,
    )

    network_name = NETWORK_TYPE_STRINGS.get(network_type, f'net{network_type}')
    print(f'\n=== Generating tuning functions ===')
    print(f'  network={network_name}, P={n_objects}, M={n_samples}, '
          f'range={range_factor}, dirs={directions}')

    # Load model
    model, input_size, norm_info = convnet_init(network_type)
    device = next(model.parameters()).device
    model.eval()

    # Register hooks on all leaf modules to capture activations
    activations = {}
    hooks = []
    for name, module in model.named_modules():
        if len(list(module.children())) == 0:  # leaf
            def _hook(mod, inp, out, n=name):
                if isinstance(out, torch.Tensor):
                    activations[n] = out.detach().cpu()
            hooks.append(module.register_forward_hook(_hook))

    # Probe to get layer sizes
    rng = np.random.default_rng(42)
    probe = np.zeros((IMAGENET_IMAGE_SIZE, IMAGENET_IMAGE_SIZE, 3), dtype=np.uint8)
    probe_t = preprocess_image(probe, input_size, norm_info).to(device)
    with torch.no_grad():
        model(probe_t)

    layer_info = {}  # name -> n_features
    for name, act in activations.items():
        n_feat = int(np.prod(act.shape[1:]))
        layer_info[name] = n_feat

    if verbose:
        print(f'  {len(layer_info)} layers detected')

    # Create random images
    base_images = rng.integers(
        0, 256,
        size=(n_objects, IMAGENET_FRAME_SIZE, IMAGENET_FRAME_SIZE, 3),
        dtype=np.uint8,
    )

    N_DIRECTIONS = len(DIRECTION_NAMES)

    # Build tuning functions per layer
    results = {}
    for lname, n_feat in layer_info.items():
        # Subsample features if too many
        n_keep = min(n_feat, N_HMAX_FEATURES)
        if n_feat > N_HMAX_FEATURES:
            feat_idx = rng.choice(n_feat, size=N_HMAX_FEATURES, replace=False)
            feat_idx.sort()
        else:
            feat_idx = np.arange(n_feat)
        results[lname] = {
            'tf': np.zeros((N_DIRECTIONS, n_objects, n_samples, n_keep), dtype=np.float32),
            'feat_idx': feat_idx,
        }

    t0 = time.time()
    n_total = len(directions) * n_objects * n_samples
    n_done = 0

    for di in directions:
        for oi in range(n_objects):
            for si in range(n_samples):
                # param_id is 1-based (1-7), j is 0-based sample index
                T = create_1d_affine_transform(range_factor, di + 1, si, n_samples)
                warped = calc_imagenet_warp_legacy(base_images[oi], T)

                # Ensure 3-channel
                if warped.ndim == 2:
                    warped = np.stack([warped] * 3, axis=-1)
                elif warped.shape[-1] == 1:
                    warped = np.concatenate([warped] * 3, axis=-1)

                img_t = preprocess_image(
                    warped.astype(np.float32), input_size, norm_info
                ).to(device)

                activations.clear()
                with torch.no_grad():
                    model(img_t)

                for lname, info in results.items():
                    if lname in activations:
                        feat = activations[lname].numpy().ravel()
                        info['tf'][di, oi, si, :] = feat[info['feat_idx']]

                n_done += 1
                if verbose and n_done % 50 == 0:
                    elapsed = time.time() - t0
                    rate = n_done / elapsed if elapsed > 0 else 0
                    print(f'    {n_done}/{n_total} ({rate:.1f} img/s)')

    # Clean up hooks
    for h in hooks:
        h.remove()

    elapsed = time.time() - t0
    if verbose:
        print(f'  Generation complete ({elapsed:.1f}s)')

    # Return just the tuning functions
    layer_tfs = {}
    for lname, info in results.items():
        layer_tfs[lname] = info['tf']

    return layer_tfs, network_name


# ============================================================================
# Step 2: Capacity analysis (core library calls)
# ============================================================================

def run_capacity_analysis(layer_tfs, n_objects, directions, verbose=True):
    """
    Run capacity analysis on each layer's tuning functions.

    For each layer, for each direction:
      1. Extract (N_NEURONS, N_SAMPLES, N_OBJECTS) tuning function
      2. Remove zero-firing neurons
      3. Call check_binary_dichotomies_capacity

    Returns dict with all MATLAB-matching result variables.
    """
    from library.check_binary_dichotomies_capacity import check_binary_dichotomies_capacity

    layer_names = list(layer_tfs.keys())
    N_LAYERS = len(layer_names)
    N_DIRECTIONS = len(DIRECTION_NAMES)

    # MATLAB result arrays
    capacity_results = np.full((N_DIRECTIONS, N_LAYERS), np.nan)
    separability_results = {}  # per (di, li)
    neuron_samples_used_results = {}
    n_support_vectors_results = {}

    print(f'\n=== Capacity analysis ({N_LAYERS} layers) ===')
    rng = np.random.default_rng(0)

    for li, lname in enumerate(layer_names):
        tf_4d = layer_tfs[lname]  # (N_DIRS, n_objects, n_samples, n_features)
        n_features = tf_4d.shape[3]

        for di in directions:
            # Extract: (n_objects, n_samples, n_features) -> (n_features, n_samples, n_objects)
            tf_slice = tf_4d[di, :n_objects, :, :].astype(np.float64)
            full_tf = tf_slice.transpose(2, 1, 0)  # (N_NEURONS, N_SAMPLES, N_OBJECTS)

            # Remove zero-firing neurons
            mean_sq = np.mean(np.mean(full_tf ** 2, axis=2), axis=1)
            nz = np.where(mean_sq > 0)[0]
            if len(nz) == 0:
                if verbose:
                    print(f'  {lname} dir={DIRECTION_NAMES[di]}: all zeros, skipping')
                continue

            current_tf = full_tf[nz, :, :]
            N = current_tf.shape[0]

            if verbose:
                print(f'  {lname} dir={DIRECTION_NAMES[di]}: '
                      f'N={N} neurons, shape={current_tf.shape}')

            try:
                t0 = time.time()
                cap, sep, neuron_counts, nsu, nsv = check_binary_dichotomies_capacity(
                    current_tf,
                    EXPECTED_PRECISION=EXPECTED_PRECISION,
                    max_samples=MAX_SAMPLES,
                    random_labeling_type=1,
                    features_type=FEATURES_TYPE,
                    verbose=int(verbose),
                    rng=rng,
                )
                elapsed = time.time() - t0

                capacity_results[di, li] = cap
                separability_results[(di, li)] = sep
                neuron_samples_used_results[(di, li)] = nsu
                n_support_vectors_results[(di, li)] = nsv

                if verbose:
                    print(f'    capacity={cap:.3f} ({elapsed:.1f}s)')

            except Exception as e:
                print(f'    FAILED: {e}')
                import traceback
                traceback.print_exc()

    return {
        'capacity_results': capacity_results,
        'separability_results': separability_results,
        'neuron_samples_used_results': neuron_samples_used_results,
        'n_support_vectors_results': n_support_vectors_results,
        'EXPECTED_PRECISION': EXPECTED_PRECISION,
        'max_samples': MAX_SAMPLES,
        'precision': 1,
        'features_type': FEATURES_TYPE,
        'layer_names': layer_names,
    }


# ============================================================================
# Step 3: Geometry analysis (core library calls)
# ============================================================================

def run_geometry_analysis(layer_tfs, n_objects, directions, verbose=True):
    """
    Run geometry analysis on each layer's tuning functions.

    For each layer, for each direction:
      1. Extract tuning function, remove zero neurons
      2. Compute center correlations via optimal_low_rank_structure
      3. Compute manifold properties via check_hierarchial_capacity

    Returns dict with all MATLAB-matching result variables.
    """
    from library.optimal_low_rank_structure import optimal_low_rank_structure
    from library.calc_manifold_properties import calc_manifold_properties

    layer_names = list(layer_tfs.keys())
    N_LAYERS = len(layer_names)
    N_DIRECTIONS = len(DIRECTION_NAMES)

    MAX_K = min(math.ceil(n_objects / 2), 46)
    N_Ks = MAX_K + 1

    # MATLAB result arrays
    best_K_results = np.full((N_DIRECTIONS, N_LAYERS), np.nan)
    effective_n_results = np.full((N_DIRECTIONS, N_LAYERS), np.nan)
    theory_capacity_results = np.full((N_DIRECTIONS, N_LAYERS), np.nan)
    correlation_spectrum_results = np.full((N_DIRECTIONS, N_LAYERS, n_objects), np.nan)
    normalized_correlation_spectrum_results = np.full((N_DIRECTIONS, N_LAYERS, n_objects), np.nan)
    mean_square_corrcoef_results = np.full((N_DIRECTIONS, N_LAYERS, N_Ks), np.nan)
    mean_abs_corrcoef_results = np.full((N_DIRECTIONS, N_LAYERS, N_Ks), np.nan)
    mean_square_correlations_results = np.full((N_DIRECTIONS, N_LAYERS, N_Ks), np.nan)
    mean_abs_correlations_results = np.full((N_DIRECTIONS, N_LAYERS, N_Ks), np.nan)
    original_correlations_results = np.full((N_DIRECTIONS, N_LAYERS, n_objects, n_objects), np.nan)
    residual_correlations_results = np.full((N_DIRECTIONS, N_LAYERS, n_objects, n_objects), np.nan)
    mean_half_width_results = np.full((N_DIRECTIONS, N_LAYERS, 1, n_objects), np.nan)
    mean_argmax_norm_results = np.full((N_DIRECTIONS, N_LAYERS, 1, n_objects), np.nan)
    mean_half_width2_results = np.full((N_DIRECTIONS, N_LAYERS, 1, n_objects), np.nan)
    mean_argmax_norm2_results = np.full((N_DIRECTIONS, N_LAYERS, 1, n_objects), np.nan)
    effective_dimension_results = np.full((N_DIRECTIONS, N_LAYERS, 1, n_objects), np.nan)
    effective_dimension2_results = np.full((N_DIRECTIONS, N_LAYERS, 1, n_objects), np.nan)
    alphac_hat_results = np.full((N_DIRECTIONS, N_LAYERS, 1, n_objects), np.nan)
    spectral_dimension_results = np.full((N_DIRECTIONS, N_LAYERS, 1, n_objects), np.nan)
    spectral_radius_results = np.full((N_DIRECTIONS, N_LAYERS, 1, n_objects), np.nan)

    print(f'\n=== Geometry analysis ({N_LAYERS} layers) ===')
    rng = np.random.default_rng(0)

    for li, lname in enumerate(layer_names):
        tf_4d = layer_tfs[lname]

        for di in directions:
            tf_slice = tf_4d[di, :n_objects, :, :].astype(np.float64)
            full_tf = tf_slice.transpose(2, 1, 0)  # (N_NEURONS, N_SAMPLES, N_OBJECTS)

            mean_sq = np.mean(np.mean(full_tf ** 2, axis=2), axis=1)
            nz = np.where(mean_sq > 0)[0]
            N = len(nz)
            effective_n_results[di, li] = N

            if N == 0:
                if verbose:
                    print(f'  {lname} dir={DIRECTION_NAMES[di]}: all zeros, skipping')
                continue

            current_tf = full_tf[nz, :, :]

            # Subtract global mean
            global_mean = np.mean(np.mean(current_tf, axis=1, keepdims=True),
                                  axis=2, keepdims=True)
            current_tf = current_tf - global_mean

            # Centers
            centers = np.mean(current_tf, axis=1)  # (N, N_OBJECTS)
            centers_norm_vec = np.sqrt(np.sum(centers ** 2, axis=0))

            # Correlation spectra
            C = centers.T @ centers
            correlation_spectrum_results[di, li, :] = np.linalg.svd(C, compute_uv=False)

            norms_outer = np.outer(centers_norm_vec, centers_norm_vec)
            norms_outer[norms_outer == 0] = 1  # avoid /0
            C0 = C / norms_outer
            original_correlations_results[di, li, :, :] = C0
            normalized_correlation_spectrum_results[di, li, :] = np.linalg.svd(C0, compute_uv=False)

            if verbose:
                print(f'  {lname} dir={DIRECTION_NAMES[di]}: N={N}')

            # Low-rank structure
            try:
                t0 = time.time()
                (Vk, Xk, Kopt, residual_norm,
                 sq_cc, abs_cc, sq_corr, abs_corr) = optimal_low_rank_structure(
                    centers, MAX_K, False, 1e-4, OPTIMIZATION_N_REPEATS, rng=rng)

                best_K_results[di, li] = Kopt
                n_k = min(len(sq_cc), N_Ks)
                mean_square_corrcoef_results[di, li, :n_k] = sq_cc[:n_k]
                mean_abs_corrcoef_results[di, li, :n_k] = abs_cc[:n_k]
                mean_square_correlations_results[di, li, :n_k] = sq_corr[:n_k]
                mean_abs_correlations_results[di, li, :n_k] = abs_corr[:n_k]

                # Residual correlations
                Xk_norm = np.sqrt(np.sum(Xk ** 2, axis=0))
                Xk_norm[Xk_norm == 0] = 1
                Ck = (Xk.T @ Xk) / np.outer(Xk_norm, Xk_norm)
                residual_correlations_results[di, li, :, :] = Ck

                elapsed = time.time() - t0
                if verbose:
                    print(f'    Low-rank K={Kopt} ({elapsed:.1f}s)')

            except Exception as e:
                print(f'    Low-rank FAILED: {e}')
                import traceback
                traceback.print_exc()
                continue

            # Manifold properties per object
            try:
                t0 = time.time()
                for j in range(n_objects):
                    center_j = centers[:, j]
                    center_norm_j = np.sqrt(np.sum(center_j ** 2))
                    if center_norm_j == 0:
                        continue

                    cF_j = current_tf[:, :, j] - center_j[:, np.newaxis]

                    # Spectral properties
                    sv = np.linalg.svd(cF_j, compute_uv=False)
                    spectral_radius_results[di, li, 0, j] = sv[0] if len(sv) > 0 else 0
                    sq_sv = sv ** 2
                    total = np.sum(sq_sv)
                    if total > 0:
                        spectral_dimension_results[di, li, 0, j] = total ** 2 / np.sum(sq_sv ** 2)

                    # Manifold properties
                    (hw1, an1, hw2, an2, ed, ed2, ac) = calc_manifold_properties(
                        cF_j, center_norm_j, kappa=0, rng=rng)

                    mean_half_width_results[di, li, 0, j] = hw1
                    mean_argmax_norm_results[di, li, 0, j] = an1
                    mean_half_width2_results[di, li, 0, j] = hw2
                    mean_argmax_norm2_results[di, li, 0, j] = an2
                    effective_dimension_results[di, li, 0, j] = ed
                    effective_dimension2_results[di, li, 0, j] = ed2
                    alphac_hat_results[di, li, 0, j] = ac

                # Theory capacity = harmonic mean of per-object alphac_hat
                ac_vals = alphac_hat_results[di, li, 0, :]
                valid = np.isfinite(ac_vals) & (ac_vals > 0)
                if np.any(valid):
                    theory_capacity_results[di, li] = 1.0 / np.mean(1.0 / ac_vals[valid])

                elapsed = time.time() - t0
                if verbose:
                    tc = theory_capacity_results[di, li]
                    print(f'    Properties: theory_cap={tc:.3f} ({elapsed:.1f}s)')

            except Exception as e:
                print(f'    Properties FAILED: {e}')
                import traceback
                traceback.print_exc()

    return {
        'OPTIMIZATION_N_REPEATS': OPTIMIZATION_N_REPEATS,
        'AllKs': np.arange(N_Ks),
        'best_K_results': best_K_results,
        'effective_n_results': effective_n_results,
        'theory_capacity_results': theory_capacity_results,
        'correlation_spectrum_results': correlation_spectrum_results,
        'normalized_correlation_spectrum_results': normalized_correlation_spectrum_results,
        'mean_square_corrcoef_results': mean_square_corrcoef_results,
        'mean_abs_corrcoef_results': mean_abs_corrcoef_results,
        'mean_square_correlations_results': mean_square_correlations_results,
        'mean_abs_correlations_results': mean_abs_correlations_results,
        'original_correlations_results': original_correlations_results,
        'residual_correlations_results': residual_correlations_results,
        'mean_half_width_results': mean_half_width_results,
        'mean_argmax_norm_results': mean_argmax_norm_results,
        'mean_half_width2_results': mean_half_width2_results,
        'mean_argmax_norm2_results': mean_argmax_norm2_results,
        'effective_dimension_results': effective_dimension_results,
        'effective_dimension2_results': effective_dimension2_results,
        'alphac_hat_results': alphac_hat_results,
        'spectral_dimension_results': spectral_dimension_results,
        'spectral_radius_results': spectral_radius_results,
        'layer_names': layer_names,
    }


# ============================================================================
# Save results (matching MATLAB variable names exactly)
# ============================================================================

def save_results(results, output_dir, network_name, range_factor, n_objects,
                 n_samples, result_type):
    """Save results to .npz with exact MATLAB variable names."""
    os.makedirs(output_dir, exist_ok=True)

    fname = (f'check_{network_name}_{result_type}_range{range_factor:.1f}'
             f'_P{n_objects}_M{n_samples}.npz')
    path = os.path.join(output_dir, fname)
    np.savez(path, **{k: v for k, v in results.items()
                      if isinstance(v, (np.ndarray, int, float, np.integer, np.floating))})
    print(f'  Saved: {path}')
    return path


# ============================================================================
# Main
# ============================================================================

def main():
    parser = argparse.ArgumentParser(description='Manifold analysis pipeline')
    parser.add_argument('--network_type', type=int, default=1,
                        help='1=alexnet, 3=resnet50, 5=vgg16 (default: 1)')
    parser.add_argument('--n_objects', type=int, default=128,
                        help='Number of objects P (default: 128)')
    parser.add_argument('--n_samples', type=int, default=None,
                        help='Samples per manifold M (default: from MATLAB table)')
    parser.add_argument('--range_factor', type=float, default=None,
                        help='Range factor (default: all 9 MATLAB values)')
    parser.add_argument('--directions', type=int, nargs='*', default=None,
                        help='Direction indices 0-6 (default: all 7)')
    parser.add_argument('--output_dir', type=str, default='./results',
                        help='Output directory (default: ./results)')
    parser.add_argument('--skip_capacity', action='store_true')
    parser.add_argument('--skip_geometry', action='store_true')
    parser.add_argument('--verbose', action='store_true', default=True)

    args = parser.parse_args()

    # Determine range factors and sample counts
    if args.range_factor is not None:
        range_factors = [args.range_factor]
        if args.n_samples is not None:
            samples_list = [args.n_samples]
        else:
            # Look up in MATLAB table
            idx = None
            for i, rf in enumerate(RANGE_FACTORS):
                if abs(rf - args.range_factor) < 1e-6:
                    idx = i
                    break
            samples_list = [SAMPLES_1D[idx]] if idx is not None else [15]
    else:
        range_factors = RANGE_FACTORS
        samples_list = SAMPLES_1D if args.n_samples is None else [args.n_samples] * len(RANGE_FACTORS)

    # Override n_samples if explicitly given
    if args.n_samples is not None:
        samples_list = [args.n_samples] * len(range_factors)

    directions = args.directions if args.directions is not None else list(range(len(DIRECTION_NAMES)))

    from smooth_manifolds_generation.feature_extraction import NETWORK_TYPE_STRINGS
    network_name = NETWORK_TYPE_STRINGS.get(args.network_type, f'net{args.network_type}')

    print(f'Pipeline: {network_name}, P={args.n_objects}, '
          f'range_factors={range_factors}, directions={directions}')
    print(f'Output: {args.output_dir}')

    os.makedirs(args.output_dir, exist_ok=True)

    for i, range_factor in enumerate(range_factors):
        n_samples = samples_list[i]
        print(f'\n{"="*60}')
        print(f'Range factor {range_factor}, M={n_samples}')
        print(f'{"="*60}')

        # Step 1: Generate tuning functions
        layer_tfs, network_name = generate_tuning_functions(
            network_type=args.network_type,
            n_objects=args.n_objects,
            n_samples=n_samples,
            range_factor=range_factor,
            directions=directions,
            verbose=args.verbose,
        )

        if not layer_tfs:
            print('  No layers extracted, skipping analysis')
            continue

        # Step 2: Capacity analysis
        if not args.skip_capacity:
            cap_results = run_capacity_analysis(
                layer_tfs, args.n_objects, directions, verbose=args.verbose)
            save_results(cap_results, args.output_dir, network_name,
                         range_factor, args.n_objects, n_samples, 'capacity')

        # Step 3: Geometry analysis
        if not args.skip_geometry:
            geo_results = run_geometry_analysis(
                layer_tfs, args.n_objects, directions, verbose=args.verbose)
            save_results(geo_results, args.output_dir, network_name,
                         range_factor, args.n_objects, n_samples, 'geometry')

    print(f'\n{"="*60}')
    print(f'Pipeline complete. Results in: {args.output_dir}')


if __name__ == '__main__':
    main()
